### ISSUE TITLE
Develop/Update Web Interface for Natural-Language Processing Extracted Interaction Network

### ISSUE THREAD

**Issue by cannin** [nrnb/GoogleSummerOfCode#142] opened 2020-01-15 15:55 UTC
### Background
This builds on the work of from #109 and found here: https://github.com/cannin/ihop-reach, where the Pathway Commons team has an extracted network of biological interactions from scientific literature (http://reach.nrnb-docker.ucsd.edu/) and a prototype interface has been developed. 

### Goal
The goal is to expand on the web interface and the data generation pipeline developed in 2019. Specific items can include, but are not limited to: 

## Frontend 
* Pagination of results 
* The search interface can be sluggish; improve the search interface 
* Convert the existing Tampermonkey script (created as part of link outs from the site) into a Chrome plugin: https://gist.github.com/cannin/4a30c1e3551b83f059c2206e491a082a

## Backend
* Incorporation of additional datasets to all users to parse the interactions better. For example, importance characteristics of the journal or citation counts of the given publications (e.g., annotating articles with journal rank from https://www.scimagojr.com/journalrank.php) 
* Update the data generation pipeline software to make updating the dataset more maintainable
* Develop Docker containers for any additional datasets that are to be included to help maintain them.

**IMPORTANT:** A good proposal would highlight two possible expansions one front-end change using Javascript (e.g., search interface optimization) and one back-end that incorporates additional data using Python (e.g., extraction of journal ranks for articles and integrating into the database)

### Difficulty Level
Difficulty level 1. Skills necessary for this project are widely applicable to many other projects. 

### Skills
* Python 
* Javascript 

### Public Repository
https://github.com/cannin/ihop-reach 

### Potential Mentors
* Augustin Luna (@cannin)
* Benjamin Gyori (@bgyori)

### Contact
[Augustin Luna (aluna AT jimmy.harvard.edu)](mailto:aluna@jimmy.harvard.edu)

**Comment by DipanshiB** [comment] 2020-01-18 10:15
I would like to take this up if its open for contribution at the moment? I have worked with GraphQL, Node.js applications with MongoDB database. @cannin

**Comment by cannin** [comment] 2020-02-28 18:40
Sorry for the delay. @DipanshiB if still interested send me a message at the email in the project description, let me know a bit about the prior work you've done, your programming background, and give me a quick idea of how you might fix the search interface to make it faster.

**Comment by PritiShaw** [comment] 2020-03-07 12:58
Hi, I am interested in this project. I am confident in ReactJS, Python, Flask, Node, Express, MongoDB. I am well aware of linux environment and I also have certification in basic Google Cloud Platform (from Coursera). 
I went through the work done last year. I can see that, for search, `lunrjs` has been used. Although I am not aware of the requirements of the project like which details are important, I think we can improve the search output by displaying vital information and only display those names which have the searched term as substring ( might fireback if there is a typo in the search key)
On the first load, search takes time, I suspect the size of the search index to be the root cause of the problem. As it is mentioned in the site that the application has over 3million sentences, I think using[ API based search](https://www.gatsbyjs.org/docs/adding-search/#use-an-api-based-search-engine) can help us improve the search experience.
Are there any competency challenge tasks prior to the application period? Can I start developing the Chrome extension?

**Comment by PritiShaw** [comment] 2020-03-08 21:36
> Are there any competency challenge tasks prior to the application period? Can I start developing the Chrome extension?

I made the basic Chrome extension using the provided [Gist](https://gist.github.com/cannin/4a30c1e3551b83f059c2206e491a082a). Requesting code review for my work available at https://github.com/PritiShaw/ihop-reach/tree/Chrome-ext-Highlight-PMC

I tested in Chrome, Chromium on Ubuntu19 and Chrome on Windows 10(results below)
![On Chrome,Win10](https://user-images.githubusercontent.com/34039705/76171555-b95a5780-61b2-11ea-9919-374074b418b7.png)

**Comment by cannin** [comment] 2020-03-09 16:33
@PritiShaw that's really nice! I updated the project description to give a better idea of what should go into a successful proposal.

**Comment by cannin** [comment] 2020-03-17 16:27
@PritiShaw if still interested in the project please send me a quick email and i'll make some additional comments

**Comment by khanspers** [comment] 2020-05-04 21:34
Active project for GSoC 2020, closing here.

**Closed by khanspers** 2020-05-04 21:34 UTC
Labels: Difficulty: 1, JavaScript, Python, web services
